language: ruby
rvm:
- 2.1

script: bash -ex ci-build.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
